name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_API: ${{ secrets.DOCKER_USERNAME }}/api
      DOCKER_IMAGE_LOAD: ${{ secrets.DOCKER_USERNAME }}/loadtester

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and train model
        run: |
          cd Niveles/4/api
          pip install -r requirements.txt
          python train_model.py

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push API image
        run: |
          docker build -t $DOCKER_IMAGE_API:latest Niveles/4/api
          docker push $DOCKER_IMAGE_API:latest

      - name: Build and push LoadTester image
        run: |
          docker build -t $DOCKER_IMAGE_LOAD:latest Niveles/4/loadtester
          docker push $DOCKER_IMAGE_LOAD:latest
